include:
  - board: nrfmicro_13
    shield: elephant42_left
  - board: nrfmicro_13
    shield: elephant42_right
include:
  - board: nrfmicro_13
    shield: elephant42_left
  - board: nrfmicro_13
    shield: elephant42_right
include:
  - board: nrfmicro_13
    shield: lotus58_left
  - board: nrfmicro_13
    shield: lotus58_right
